#!/bin/bash
# /etc/init.d/linger_counter

### BEGIN INIT INFO
# Provides:          linger_counter
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: linger_counter
# Description:       This service is used to display Linger's results on a display
### END INIT INFO

case "$1" in
    start)
        echo "Starting linger_counter" > /dev/tty1
        sudo /home/pi/linger/linger_counter.py 1> /dev/tty1 2>/home/pi/linger/log
        ;;
    stop)
        echo "Stopping linger_counter" > /dev/tty1
        sudo kill `ps -eo pid,command | grep "linger_counter.py" | grep -v grep | head -1 | awk '{print $1}'`1>/dev/null 2>/home/pi/linger/log
        echo "Done" > /dev/tty1
        ;;
    *)
        echo "Usage: /etc/init.d/linger_counter start|stop"
        exit 1
        ;;
esac

exit 0
